feat: authentication folder
Orfium/toolbox pull request #10
Opened 2022-06-09 07:22 UTC by Christos-Zacharopoulos

## Description

This PR introduces the Authentication module. It's an abstraction of auth0 react package that provides the minimum functions that we might need and the allows for overrides on the Provider config.

Ticket: [DEV-39](https://orfium.atlassian.net/browse/DEV-39)

## Test Plan

Tested that our handling on the package works as expected.
√ renders without crashing 
√ renders the test component 
√ redirects to login if not authenticated 
√ renders the loading while its authenticating

2022-06-16 07:13 UTC, panvourtsis requested changes

2022-06-16 07:13 UTC, panvourtsis commented on documentation/docs/modules/authentication.md
> +### 1. Set up environment variables.
I would expect here to explicit define the .env file

2022-06-16 07:13 UTC, panvourtsis commented on documentation/docs/modules/authentication.md
> +So, yeah. It's there but don't use it. If you need something more , please contact the maintainers of `toolbox` to see if it's really needed in order to add it as a default.
This is so confusing, can we write a section for someone that wants to go deeper and read more? Also maybe change these to bold

2022-06-16 07:13 UTC, panvourtsis commented on documentation/docs/modules/authentication.md
> +### 3. Wait for it
This is Important so maybe we can add it to the title.

2022-06-16 07:13 UTC, panvourtsis commented on documentation/docs/modules/authentication.md
> +## Usage
This is not Usage but Example - Usage are the steps above

2022-06-16 11:25 UTC, Christos-Zacharopoulos commented on documentation/docs/modules/authentication.md
> +So, yeah. It's there but don't use it. If you need something more , please contact the maintainers of `toolbox` to see if it's really needed in order to add it as a default.
I can add a link to the corresponding documentation on this, but I don't think we are ready to provide too much insight on how to set this up. I mean, until now I have integrated this to 4 apps and none needed any overrides! 

I think we could stick with the official documentation on this and revisit this specific point after integration with a couple of projects and have some real use case scenarios.

2022-06-16 12:51 UTC, Christos-Zacharopoulos commented on documentation/docs/modules/authentication.md
> +So, yeah. It's there but don't use it. If you need something more , please contact the maintainers of `toolbox` to see if it's really needed in order to add it as a default.
Also, any change to the initialization could end up with different auth experience for the end user. So maybe it's better to remove the overrides all together? :/

2022-06-17 07:46 UTC, panvourtsis commented on documentation/docs/modules/authentication.md
> +So, yeah. It's there but don't use it. If you need something more , please contact the maintainers of `toolbox` to see if it's really needed in order to add it as a default.
I think that we should, why have it if we don't use it right? We will avoid any problematic use

2022-06-20 08:56 UTC, merged